export const EGYPTIAN_UNIVERSITIES = [
  "Cairo University",
  "Ain Shams University",
  "Alexandria University",
  "Mansoura University",
  "Helwan University",
  "Zagazig University",
  "Tanta University",
  "Assiut University",
  "Suez Canal University",
  "Minia University",
  "Monufia University",
  "Banha University",
  "Fayoum University",
  "Sohag University",
  "Beni-Suef University",
  "Aswan University",
  "Damietta University",
  "Port Said University",
  "Kafr El-Sheikh University",
  "Damanhour University",
  "Suez University",
  "Sadat City University",
  "Arish University",
  "Luxor University",
  "New Valley University",
  "Matrouh University",
  "American University in Cairo (AUC)",
  "German University in Cairo (GUC)",
  "British University in Egypt (BUE)",
  "Future University in Egypt (FUE)",
  "Heliopolis University",
  "Misr University for Science and Technology (MUST)",
  "October 6 University (O6U)",
  "Nile University",
  "Modern Sciences and Arts University (MSA)",
  "Arab Academy for Science, Technology and Maritime Transport (AASTMT)",
  "Egyptian Russian University (ERU)",
  "Pharos University in Alexandria (PUA)",
  "El Gouna Technical University",
  "Galala University",
  "King Salman International University (KSIU)",
  "New Alamein City University",
  "E-Just (Egypt-Japan University of Science and Technology)"
];

export const EGYPT_LOCATIONS = [
  "Cairo",
  "Giza",
  "Alexandria",
  "Qalyubia",
  "Dakahlia",
  "Gharbia",
  "Monufia",
  "Sharqia",
  "Beheira",
  "Damietta",
  "Matrouh",
  "Suez",
  "Ismailia",
  "Port Said",
  "North Sinai",
  "South Sinai",
  "Faiyum",
  "Beni Suef",
  "Minya",
  "Asyut",
  "Sohag",
  "Qena",
  "Luxor",
  "Aswan",
  "Red Sea",
  "New Valley",
  "Kafr El-Sheikh"
];
